### ISSUE TITLE
Stuck Sending....

### ISSUE THREAD

**Issue by jab1000** [spatie/Mailcoach#30]
I setup everything - campaign, email and set it to send to a list of about 105,000 email address via SES.  Everything went great until it hit 57,993 emails sent out and has been "trying to send" now for the past 5'ish hours without truly sending any more.... still stuck on "Campaign [x] is sending to 57993/57993 subscribers of [y]".

Thoughts on how to kick it back again when this happens?

**Comment by riasvdv** [comment]
Are there any exceptions in your log that could help us find out what happened?

**Comment by freekmurze** [comment]
That's unfortunate, luckily we have some code in place that allows you to resume sending without sending mails again to people that already got it.

In the `mailcoach_sends` table each row represent a mail that should be sent or has been sent (if `sent_at` is `null` that mail hasn't been sent yet. 

There are two scenarios on what could have gone wrong. Either the job that creates a those records in the `mailcoach_sends` went wrong (maybe it timed out), or there was something going wrong with the jobs that send out individual mails (you might have hit a limit on the email sending side).

In both scenarios, there are ways to resume the sending the campaign, but to know the best course of action, as suggested by my colleague @riasvdv,  we need to know what went wrong.

In the Outbox tab of a sent campaign, you can see failed sends. Are there any there? Could you also take a look at `/horizon` and take a look if there are any failed jobs? If so, could you post the exception and trace displayed there?

**Comment by jab1000** [comment]
Only 1 failed job and here is the stack trace for it -- no less the timing of it makes sense for when it seemed to "die".

```
ID - 160
Queue - send-campaign
Tags - Spatie\Mailcoach\Models\Campaign:5
Failed At - 2020-03-30 11:39:59
```

```
Illuminate\Queue\MaxAttemptsExceededException: Spatie\Mailcoach\Jobs\SendCampaignJob has been attempted too many times or run too long. The job may have previously timed out. in /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:647
--
Stack trace:
#0 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(163): Illuminate\Queue\Worker->maxAttemptsExceededException()
#1 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1399): Illuminate\Queue\Worker->Illuminate\Queue\{closure}()
#2 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(379): Illuminate\Database\Eloquent\Model->transformModelValue()
#3 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(358): Illuminate\Database\Eloquent\Model->getAttributeValue()
#4 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1567): Illuminate\Database\Eloquent\Model->getAttribute()
#5 /var/www/mailcoach/vendor/spatie/laravel-mailcoach/src/Models/Subscriber.php(107): Illuminate\Database\Eloquent\Model->__get()
#6 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(465): Spatie\Mailcoach\Models\Subscriber->getStatusAttribute()
#7 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1392): Illuminate\Database\Eloquent\Model->mutateAttribute()
#8 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(379): Illuminate\Database\Eloquent\Model->transformModelValue()
#9 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(358): Illuminate\Database\Eloquent\Model->getAttributeValue()
#10 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1567): Illuminate\Database\Eloquent\Model->getAttribute()
#11 /var/www/mailcoach/vendor/spatie/laravel-mailcoach/src/Models/Subscriber.php(226): Illuminate\Database\Eloquent\Model->__get()
#12 /var/www/mailcoach/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendCampaignAction.php(104): Spatie\Mailcoach\Models\Subscriber->isSubscribed()
#13 /var/www/mailcoach/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendCampaignAction.php(76): Spatie\Mailcoach\Actions\Campaigns\SendCampaignAction->isValidSubscriptionForEmailList()
#14 /var/www/mailcoach/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendCampaignAction.php(62): Spatie\Mailcoach\Actions\Campaigns\SendCampaignAction->sendMail()
#15 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(62): Spatie\Mailcoach\Actions\Campaigns\SendCampaignAction->Spatie\Mailcoach\Actions\Campaigns\{closure}()
#16 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Concerns\{closure}()
#17 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(66): Illuminate\Database\Eloquent\Builder->chunk()
#18 /var/www/mailcoach/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendCampaignAction.php(63): Illuminate\Database\Eloquent\Builder->each()
#19 /var/www/mailcoach/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendCampaignAction.php(26): Spatie\Mailcoach\Actions\Campaigns\SendCampaignAction->sendMailsForCampaign()
#20 /var/www/mailcoach/vendor/spatie/laravel-mailcoach/src/Jobs/SendCampaignJob.php(37): Spatie\Mailcoach\Actions\Campaigns\SendCampaignAction->execute()
#21 [internal function]: Spatie\Mailcoach\Jobs\SendCampaignJob->handle()
#22 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#23 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#24 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#25 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#26 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#27 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#28 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#29 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#31 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow()
#32 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#33 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then()
#35 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#36 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#37 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Jobs\Job->fire()
#38 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process()
#39 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob()
#40 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon()
#41 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker()
#42 /var/www/mailcoach/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#43 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#44 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#45 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#46 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#47 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#48 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#49 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#50 /var/www/mailcoach/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#51 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#52 /var/www/mailcoach/vendor/symfony/console/Application.php(912): Illuminate\Console\Command->run()
#53 /var/www/mailcoach/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#54 /var/www/mailcoach/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#55 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#56 /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(130): Illuminate\Console\Application->run()
#57 /var/www/mailcoach/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#58 {main}
```

**Comment by jab1000** [comment]
As for the "outbox" --> Failed = 0 and Pending = 0

FYI, when I do a quick custom query on mailcoach_sends the count of "sent_at" being null is 0.  Here is my query just in case:
```
select count(id)
from mailcoach_sends
where sent_at is null;
```

About 7ish pm yesterday I did do another email send to a different list (FYI, would love to be able to send to more than 1 list at a time) which was 125k emails -- yes, it went fully.  I was able to see that it would "load up" the "send mail" job with all 125k email and per mailcoach web gui it was "sent".... this leads me to believe the "loading" of the original campaign "died" at the 57,993 and then never restarted/corrected itself.

Any other questions let me know.

**Comment by freekmurze** [comment]
I'm thinking the `SendCampaignJob` timed out. To fix this you can set the timeouts in the `horizon.php` config file to higher values. I updated the default values for them in our docs a couple of days ago.
https://mailcoach.app/docs/v2/package/general/installation-and-setup#install-horizon

After you've updated the time out and restarted the horizon process you can retry the job in the Horizon interface (there's logic in place to make sure that no mails will be sent to people that already received the campaign.

Alternatively, you could also manually resend the campaign

```php
$campaign = Campaign::find($idOfTheCampaign);

dispatch(new Spatie\Mailcoach\Jobs\SendCampaignJob($campaign));
```

Let us know if this works for you.

**Comment by jab1000** [comment]
I did update the times yesterday afternoon but this campaign had already failed so possibly then why the one sent last night (EST) it did fully send.

I will try to just re-try the job and see if it starts going.

Thanks!

**Comment by jab1000** [comment]
FYI, after "restarting" the previously failed job, the mail-send job has 49k+ emails in there so it looks like all is good now again.  

Thanks!

**Comment by freekmurze** [comment]
Nice, good to hear!
