### ISSUE TITLE
Error when sending newsletter

### ISSUE THREAD

**Issue by labomatik** [spatie/Mailcoach#40]
Got today an error when sending the newsletter, i can see the process in sending but noting goes out

```
[previous exception] [object] (ErrorException(code: 0): DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1540 at /var/www/html/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/PrepareEmailHtmlAction.php:32)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/PrepareEmailHtmlAction.php(32): DOMDocument->loadHTML()
#2 /var/www/html/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/PrepareEmailHtmlAction.php(16): Spatie\\Mailcoach\\Actions\\Campaigns\\PrepareEmailHtmlAction->ensureValidHtml()
#3 /var/www/html/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendCampaignAction.php(34): Spatie\\Mailcoach\\Actions\\Campaigns\\PrepareEmailHtmlAction->execute()
#4 /var/www/html/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendCampaignAction.php(24): Spatie\\Mailcoach\\Actions\\Campaigns\\SendCampaignAction->prepareEmailHtml()
#5 /var/www/html/vendor/spatie/laravel-mailcoach/src/Jobs/SendCampaignJob.php(35): Spatie\\Mailcoach\\Actions\\Campaigns\\SendCampaignAction->execute()
#6 [internal function]: Spatie\\Mailcoach\\Jobs\\SendCampaignJob->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#27 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#28 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#35 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#37 /var/www/html/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run()
#38 /var/www/html/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#39 /var/www/html/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(130): Illuminate\\Console\\Application->run()
#42 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#43 {main}
"}
```

**Comment by freekmurze** [comment]
Could you let us know the version number of Mailcoach you are using?

**Comment by labomatik** [comment]
Mailcoach 2.11.8
 by SPATIE

**Comment by rubenvanassche** [comment]
Hi @labomatik could you please update Mailcoach to latest version and test again? If that doesn't work, could you provide the html you're using for the email? It seems like PHP DOMDocument is complaining about something that's not correct.

**Comment by rubenvanassche** [comment]
Closing due to inactivity
